service: serverless-collaborative-booking-api
provider:
  name: aws
  runtime: nodejs6.10
functions:
  hello:
    handler: handler.hello
    events:
     - http:
        path: /
        method: get
        authorizer: auth
  auth:
    handler: handler.auth
