service: serverless-collaborative-booking-api
provider:
  name: aws
  runtime: nodejs6.10
functions:
  hello:
    handler: handler.hello
    events:
     - http:
        path: /
        method: get
        authorizer: auth
        
  saveComment:
    handler: handler.saveComment
    events:
     - http:
        path: /add
        method: post
     - http:
        path: /delete
        method: delete

  auth:
    handler: handler.auth
